/* This file was generated by SableCC (http://www.sablecc.org/). */

package Syntax.node;

import Syntax.analysis.*;

@SuppressWarnings("nls")
public final class AArrayTypeCombination extends PTypeCombination
{
    private PTypeCombination _typeCombination_;

    public AArrayTypeCombination()
    {
        // Constructor
    }

    public AArrayTypeCombination(
        @SuppressWarnings("hiding") PTypeCombination _typeCombination_)
    {
        // Constructor
        setTypeCombination(_typeCombination_);

    }

    @Override
    public Object clone()
    {
        return new AArrayTypeCombination(
            cloneNode(this._typeCombination_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayTypeCombination(this);
    }

    public PTypeCombination getTypeCombination()
    {
        return this._typeCombination_;
    }

    public void setTypeCombination(PTypeCombination node)
    {
        if(this._typeCombination_ != null)
        {
            this._typeCombination_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeCombination_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeCombination_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeCombination_ == child)
        {
            this._typeCombination_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typeCombination_ == oldChild)
        {
            setTypeCombination((PTypeCombination) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
