/* This file was generated by SableCC (http://www.sablecc.org/). */

package Syntax.node;

import Syntax.analysis.*;

@SuppressWarnings("nls")
public final class AArrayExpr extends PExpr
{
    private TId _id_;
    private PExpr _i_;
    private PExpr _init_;

    public AArrayExpr()
    {
        // Constructor
    }

    public AArrayExpr(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PExpr _i_,
        @SuppressWarnings("hiding") PExpr _init_)
    {
        // Constructor
        setId(_id_);

        setI(_i_);

        setInit(_init_);

    }

    @Override
    public Object clone()
    {
        return new AArrayExpr(
            cloneNode(this._id_),
            cloneNode(this._i_),
            cloneNode(this._init_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayExpr(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PExpr getI()
    {
        return this._i_;
    }

    public void setI(PExpr node)
    {
        if(this._i_ != null)
        {
            this._i_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._i_ = node;
    }

    public PExpr getInit()
    {
        return this._init_;
    }

    public void setInit(PExpr node)
    {
        if(this._init_ != null)
        {
            this._init_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._init_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._i_)
            + toString(this._init_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._i_ == child)
        {
            this._i_ = null;
            return;
        }

        if(this._init_ == child)
        {
            this._init_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._i_ == oldChild)
        {
            setI((PExpr) newChild);
            return;
        }

        if(this._init_ == oldChild)
        {
            setInit((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
