/* This file was generated by SableCC (http://www.sablecc.org/). */

package Syntax.node;

import Syntax.analysis.*;

@SuppressWarnings("nls")
public final class AIfExpr extends PExpr
{
    private PExpr _c_;
    private PExpr _t_;
    private PExpr _f_;

    public AIfExpr()
    {
        // Constructor
    }

    public AIfExpr(
        @SuppressWarnings("hiding") PExpr _c_,
        @SuppressWarnings("hiding") PExpr _t_,
        @SuppressWarnings("hiding") PExpr _f_)
    {
        // Constructor
        setC(_c_);

        setT(_t_);

        setF(_f_);

    }

    @Override
    public Object clone()
    {
        return new AIfExpr(
            cloneNode(this._c_),
            cloneNode(this._t_),
            cloneNode(this._f_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfExpr(this);
    }

    public PExpr getC()
    {
        return this._c_;
    }

    public void setC(PExpr node)
    {
        if(this._c_ != null)
        {
            this._c_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._c_ = node;
    }

    public PExpr getT()
    {
        return this._t_;
    }

    public void setT(PExpr node)
    {
        if(this._t_ != null)
        {
            this._t_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t_ = node;
    }

    public PExpr getF()
    {
        return this._f_;
    }

    public void setF(PExpr node)
    {
        if(this._f_ != null)
        {
            this._f_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._f_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._c_)
            + toString(this._t_)
            + toString(this._f_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._c_ == child)
        {
            this._c_ = null;
            return;
        }

        if(this._t_ == child)
        {
            this._t_ = null;
            return;
        }

        if(this._f_ == child)
        {
            this._f_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._c_ == oldChild)
        {
            setC((PExpr) newChild);
            return;
        }

        if(this._t_ == oldChild)
        {
            setT((PExpr) newChild);
            return;
        }

        if(this._f_ == oldChild)
        {
            setF((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
