/* This file was generated by SableCC (http://www.sablecc.org/). */

package Syntax.node;

import java.util.*;
import Syntax.analysis.*;

@SuppressWarnings("nls")
public final class AMethodDeclaration extends PDeclaration
{
    private TId _id_;
    private final LinkedList<PTypeField> _typeField_ = new LinkedList<PTypeField>();
    private PTypeCombination _typeCombination_;
    private PExpr _expr_;

    public AMethodDeclaration()
    {
        // Constructor
    }

    public AMethodDeclaration(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<PTypeField> _typeField_,
        @SuppressWarnings("hiding") PTypeCombination _typeCombination_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setId(_id_);

        setTypeField(_typeField_);

        setTypeCombination(_typeCombination_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AMethodDeclaration(
            cloneNode(this._id_),
            cloneList(this._typeField_),
            cloneNode(this._typeCombination_),
            cloneNode(this._expr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodDeclaration(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PTypeField> getTypeField()
    {
        return this._typeField_;
    }

    public void setTypeField(List<PTypeField> list)
    {
        this._typeField_.clear();
        this._typeField_.addAll(list);
        for(PTypeField e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public PTypeCombination getTypeCombination()
    {
        return this._typeCombination_;
    }

    public void setTypeCombination(PTypeCombination node)
    {
        if(this._typeCombination_ != null)
        {
            this._typeCombination_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeCombination_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._typeField_)
            + toString(this._typeCombination_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._typeField_.remove(child))
        {
            return;
        }

        if(this._typeCombination_ == child)
        {
            this._typeCombination_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PTypeField> i = this._typeField_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTypeField) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._typeCombination_ == oldChild)
        {
            setTypeCombination((PTypeCombination) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
