/* This file was generated by SableCC (http://www.sablecc.org/). */

package Syntax.node;

import Syntax.analysis.*;

@SuppressWarnings("nls")
public final class AOrExpr extends PExpr
{
    private PExpr _l_;
    private PExpr _r_;

    public AOrExpr()
    {
        // Constructor
    }

    public AOrExpr(
        @SuppressWarnings("hiding") PExpr _l_,
        @SuppressWarnings("hiding") PExpr _r_)
    {
        // Constructor
        setL(_l_);

        setR(_r_);

    }

    @Override
    public Object clone()
    {
        return new AOrExpr(
            cloneNode(this._l_),
            cloneNode(this._r_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrExpr(this);
    }

    public PExpr getL()
    {
        return this._l_;
    }

    public void setL(PExpr node)
    {
        if(this._l_ != null)
        {
            this._l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l_ = node;
    }

    public PExpr getR()
    {
        return this._r_;
    }

    public void setR(PExpr node)
    {
        if(this._r_ != null)
        {
            this._r_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._r_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._l_)
            + toString(this._r_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._l_ == child)
        {
            this._l_ = null;
            return;
        }

        if(this._r_ == child)
        {
            this._r_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._l_ == oldChild)
        {
            setL((PExpr) newChild);
            return;
        }

        if(this._r_ == oldChild)
        {
            setR((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
