/* This file was generated by SableCC (http://www.sablecc.org/). */

package Syntax.node;

import Syntax.analysis.*;

@SuppressWarnings("nls")
public final class ATypeField extends PTypeField
{
    private TId _v_;
    private PTypeCombination _t_;

    public ATypeField()
    {
        // Constructor
    }

    public ATypeField(
        @SuppressWarnings("hiding") TId _v_,
        @SuppressWarnings("hiding") PTypeCombination _t_)
    {
        // Constructor
        setV(_v_);

        setT(_t_);

    }

    @Override
    public Object clone()
    {
        return new ATypeField(
            cloneNode(this._v_),
            cloneNode(this._t_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeField(this);
    }

    public TId getV()
    {
        return this._v_;
    }

    public void setV(TId node)
    {
        if(this._v_ != null)
        {
            this._v_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._v_ = node;
    }

    public PTypeCombination getT()
    {
        return this._t_;
    }

    public void setT(PTypeCombination node)
    {
        if(this._t_ != null)
        {
            this._t_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._t_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._v_)
            + toString(this._t_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._v_ == child)
        {
            this._v_ = null;
            return;
        }

        if(this._t_ == child)
        {
            this._t_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._v_ == oldChild)
        {
            setV((TId) newChild);
            return;
        }

        if(this._t_ == oldChild)
        {
            setT((PTypeCombination) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
