/* This file was generated by SableCC (http://www.sablecc.org/). */

package Syntax.node;

import Syntax.analysis.*;

@SuppressWarnings("nls")
public final class TArray extends Token
{
    public TArray()
    {
        super.setText("array");
    }

    public TArray(int line, int pos)
    {
        super.setText("array");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArray(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArray(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TArray text.");
    }
}
