/* This file was generated by SableCC (http://www.sablecc.org/). */

package Syntax.node;

import Syntax.analysis.*;

@SuppressWarnings("nls")
public final class TNil extends Token
{
    public TNil()
    {
        super.setText("nil");
    }

    public TNil(int line, int pos)
    {
        super.setText("nil");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNil(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNil(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNil text.");
    }
}
