
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 19 16:19:17 CST 2008
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 19;
  public static final int FUNCTION = 43;
  public static final int GE = 25;
  public static final int UMINUS = 17;
  public static final int LPAREN = 8;
  public static final int INT = 4;
  public static final int ARRAY = 29;
  public static final int FOR = 34;
  public static final int MINUS = 16;
  public static final int RPAREN = 9;
  public static final int SEMICOLON = 7;
  public static final int AND = 26;
  public static final int LT = 22;
  public static final int TYPE = 45;
  public static final int NIL = 42;
  public static final int IN = 38;
  public static final int OR = 27;
  public static final int COMMA = 5;
  public static final int PLUS = 15;
  public static final int ASSIGN = 28;
  public static final int IF = 30;
  public static final int DOT = 14;
  public static final int ID = 2;
  public static final int LE = 23;
  public static final int OF = 40;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NEQ = 21;
  public static final int BREAK = 41;
  public static final int EQ = 20;
  public static final int LBRACK = 10;
  public static final int TIMES = 18;
  public static final int COLON = 6;
  public static final int LBRACE = 12;
  public static final int ELSE = 32;
  public static final int RBRACK = 11;
  public static final int TO = 35;
  public static final int WHILE = 33;
  public static final int LET = 37;
  public static final int THEN = 31;
  public static final int RBRACE = 13;
  public static final int END = 39;
  public static final int STRING = 3;
  public static final int GT = 24;
  public static final int VAR = 44;
  public static final int DO = 36;
}
