/* The following code was generated by JFlex 1.4.3 on 09-4-2 ÏÂÎç10:57 */

/* JFlex example: part of Java language lexer specification */

package Parse;

import java_cup.runtime.*;
import ErrorMsg.ErrorMsg;

/**
 * This class is a simple example lexer.
 */

public class Lexer extends sym implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int NESTED_COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\32"+
    "\3\0\1\55\1\0\1\37\1\40\1\50\1\46\1\34\1\47\1\45"+
    "\1\51\12\33\1\35\1\36\1\53\1\52\1\54\1\0\1\61\32\62"+
    "\1\41\1\57\1\42\1\60\1\5\1\0\1\6\1\11\1\23\1\14"+
    "\1\12\1\21\1\4\1\26\1\25\1\4\1\13\1\16\1\4\1\20"+
    "\1\15\1\27\1\4\1\7\1\17\1\24\1\22\1\30\1\31\1\4"+
    "\1\10\1\4\1\43\1\56\1\44\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\15\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\2\2\4\3\1\34\1\35"+
    "\5\3\1\36\1\3\1\37\1\40\2\3\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\0\1\47\1\50\1\51"+
    "\1\52\1\0\1\53\1\0\1\54\1\55\3\3\1\56"+
    "\1\57\1\60\1\61\3\3\1\62\1\3\1\0\1\63"+
    "\2\3\1\64\1\3\1\65\1\66\1\3\1\67\1\70"+
    "\1\71\1\3\1\72\2\3\1\73";

  private static int [] zzUnpackAction() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\231\0\377\0\u0132"+
    "\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca"+
    "\0\u02fd\0\u0330\0\u0363\0\231\0\u0396\0\231\0\u03c9\0\231"+
    "\0\231\0\231\0\231\0\231\0\231\0\231\0\231\0\231"+
    "\0\231\0\u03fc\0\u042f\0\231\0\u0462\0\u0495\0\231\0\231"+
    "\0\u04c8\0\231\0\u04fb\0\u052e\0\u0561\0\u0594\0\u05c7\0\u05fa"+
    "\0\u062d\0\377\0\377\0\u0660\0\u0693\0\u06c6\0\u06f9\0\u072c"+
    "\0\377\0\u075f\0\377\0\377\0\u0792\0\u07c5\0\231\0\231"+
    "\0\231\0\231\0\231\0\231\0\u07f8\0\231\0\231\0\231"+
    "\0\231\0\u082b\0\231\0\u085e\0\231\0\231\0\u0891\0\u08c4"+
    "\0\u08f7\0\377\0\377\0\377\0\377\0\u092a\0\u095d\0\u0990"+
    "\0\377\0\u09c3\0\u09f6\0\231\0\u0a29\0\u0a5c\0\377\0\u0a8f"+
    "\0\377\0\377\0\u0ac2\0\231\0\377\0\377\0\u0af5\0\377"+
    "\0\u0b28\0\u0b5b\0\377";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\4\1\10\2\7\1\11"+
    "\1\12\1\7\1\13\1\14\1\15\1\7\1\16\1\17"+
    "\2\7\1\20\1\21\2\7\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\3\4\1\7\1\51\2\0\27\51"+
    "\1\52\24\51\1\53\3\51\2\6\1\0\45\6\1\54"+
    "\1\55\11\6\65\0\1\6\64\0\26\7\1\0\1\7"+
    "\26\0\1\7\4\0\3\7\1\56\22\7\1\0\1\7"+
    "\26\0\1\7\4\0\3\7\1\57\22\7\1\0\1\7"+
    "\26\0\1\7\4\0\12\7\1\60\1\7\1\61\11\7"+
    "\1\0\1\7\26\0\1\7\4\0\11\7\1\62\14\7"+
    "\1\0\1\7\26\0\1\7\4\0\15\7\1\63\10\7"+
    "\1\0\1\7\26\0\1\7\4\0\6\7\1\64\17\7"+
    "\1\0\1\7\26\0\1\7\4\0\21\7\1\65\4\7"+
    "\1\0\1\7\26\0\1\7\4\0\11\7\1\66\4\7"+
    "\1\67\7\7\1\0\1\7\26\0\1\7\4\0\4\7"+
    "\1\70\4\7\1\71\10\7\1\72\3\7\1\0\1\7"+
    "\26\0\1\7\4\0\14\7\1\73\1\74\10\7\1\0"+
    "\1\7\26\0\1\7\4\0\2\7\1\75\23\7\1\0"+
    "\1\7\26\0\1\7\4\0\22\7\1\76\3\7\1\0"+
    "\1\7\26\0\1\7\33\0\1\25\101\0\1\77\61\0"+
    "\1\100\61\0\1\101\64\0\1\102\1\0\1\103\60\0"+
    "\1\104\10\0\1\51\2\0\27\51\1\0\24\51\1\0"+
    "\3\51\1\0\3\105\3\0\1\106\10\0\1\107\3\0"+
    "\1\110\5\0\1\111\1\112\23\0\1\113\1\114\53\0"+
    "\1\115\61\0\1\116\16\0\3\7\1\117\22\7\1\0"+
    "\1\7\26\0\1\7\4\0\6\7\1\120\17\7\1\0"+
    "\1\7\26\0\1\7\4\0\13\7\1\121\12\7\1\0"+
    "\1\7\26\0\1\7\4\0\10\7\1\122\15\7\1\0"+
    "\1\7\26\0\1\7\4\0\20\7\1\123\5\7\1\0"+
    "\1\7\26\0\1\7\4\0\12\7\1\124\13\7\1\0"+
    "\1\7\26\0\1\7\4\0\3\7\1\125\22\7\1\0"+
    "\1\7\26\0\1\7\4\0\14\7\1\126\11\7\1\0"+
    "\1\7\26\0\1\7\4\0\23\7\1\127\2\7\1\0"+
    "\1\7\26\0\1\7\4\0\6\7\1\130\17\7\1\0"+
    "\1\7\26\0\1\7\4\0\3\7\1\131\22\7\1\0"+
    "\1\7\26\0\1\7\4\0\21\7\1\132\4\7\1\0"+
    "\1\7\26\0\1\7\1\0\3\105\53\0\1\6\36\0"+
    "\1\133\34\0\1\134\33\0\2\134\14\0\4\134\4\0"+
    "\2\7\1\135\23\7\1\0\1\7\26\0\1\7\4\0"+
    "\2\7\1\136\23\7\1\0\1\7\26\0\1\7\4\0"+
    "\6\7\1\137\17\7\1\0\1\7\26\0\1\7\4\0"+
    "\17\7\1\140\6\7\1\0\1\7\26\0\1\7\4\0"+
    "\6\7\1\141\17\7\1\0\1\7\26\0\1\7\4\0"+
    "\14\7\1\142\11\7\1\0\1\7\26\0\1\7\4\0"+
    "\12\7\1\143\13\7\1\0\1\7\26\0\1\7\33\0"+
    "\1\144\33\0\4\7\1\145\21\7\1\0\1\7\26\0"+
    "\1\7\4\0\7\7\1\146\16\7\1\0\1\7\26\0"+
    "\1\7\4\0\20\7\1\147\5\7\1\0\1\7\26\0"+
    "\1\7\4\0\6\7\1\150\17\7\1\0\1\7\26\0"+
    "\1\7\4\0\21\7\1\151\4\7\1\0\1\7\26\0"+
    "\1\7\4\0\11\7\1\152\14\7\1\0\1\7\26\0"+
    "\1\7\4\0\14\7\1\153\11\7\1\0\1\7\26\0"+
    "\1\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2958];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\15\1\1\11\1\1\1\11"+
    "\1\1\12\11\2\1\1\11\2\1\2\11\1\1\1\11"+
    "\24\1\6\11\1\0\4\11\1\0\1\11\1\0\2\11"+
    "\14\1\1\0\1\11\7\1\1\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  sym sym;
  int level = 0;
  
  private void newline() {
  	errorMsg.newline(yychar);
  }
  
  private void err(int pos,String s) {
  	errorMsg.error(pos,s);
  }
  
  private void err(String s) {
  	err(yychar,s);
  }
  
  private ErrorMsg errorMsg;

  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }
    
  Lexer(java.io.InputStream s,ErrorMsg e) {
  	this(s);
  	errorMsg = e;
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      /* your code goes here */
  yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [131] { /* ignore */ }");
          { /* ignore */
          }
        case 60: break;
        case 1: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [159] { throw new Error(\"Illegal character <\"+ yytext()+\">\"); }");
          { throw new Error("Illegal character <"+ yytext()+">");
          }
        case 61: break;
        case 29: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [85] { return symbol(sym.OF); }");
          { return symbol(sym.OF);
          }
        case 62: break;
        case 30: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [87] { return symbol(sym.TO); }");
          { return symbol(sym.TO);
          }
        case 63: break;
        case 11: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [107] { return symbol(sym.L2); }");
          { return symbol(sym.L2);
          }
        case 64: break;
        case 16: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [112] { return symbol(sym.ADD); }");
          { return symbol(sym.ADD);
          }
        case 65: break;
        case 46: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [78] { return symbol(sym.END); }");
          { return symbol(sym.END);
          }
        case 66: break;
        case 41: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [145] { string.append(\'\\t\'); }");
          { string.append('\t');
          }
        case 67: break;
        case 4: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [98] { string.setLength(0); yybegin(STRING); }");
          { string.setLength(0); yybegin(STRING);
          }
        case 68: break;
        case 3: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [95] { return symbol(sym.IDENTIFIER,yytext()); }");
          { return symbol(sym.IDENTIFIER,yytext());
          }
        case 69: break;
        case 9: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [105] { return symbol(sym.L1); }");
          { return symbol(sym.L1);
          }
        case 70: break;
        case 23: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [122] { return symbol(sym.AND); }");
          { return symbol(sym.AND);
          }
        case 71: break;
        case 33: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [124] { return symbol(sym.ASSIGN); }");
          { return symbol(sym.ASSIGN);
          }
        case 72: break;
        case 19: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [115] { return symbol(sym.DIV); }");
          { return symbol(sym.DIV);
          }
        case 73: break;
        case 27: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [155] { string.append(\'\\\\\'); }");
          { string.append('\\');
          }
        case 74: break;
        case 35: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [127] { level = 1; yybegin(NESTED_COMMENT); }");
          { level = 1; yybegin(NESTED_COMMENT);
          }
        case 75: break;
        case 39: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [149] { string.append(\'\\r\'); }");
          { string.append('\r');
          }
        case 76: break;
        case 44: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [136] { --level; if(level == 0) yybegin(YYINITIAL); }");
          { --level; if(level == 0) yybegin(YYINITIAL);
          }
        case 77: break;
        case 26: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [141] { yybegin(YYINITIAL); "+ZZ_NL+"                                   return symbol(sym.STRING, "+ZZ_NL+"                                   string.toString()); }");
          { yybegin(YYINITIAL); 
                                   return symbol(sym.STRING, 
                                   string.toString());
          }
        case 78: break;
        case 56: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [74] { return symbol(sym.ARRAY); }");
          { return symbol(sym.ARRAY);
          }
        case 79: break;
        case 21: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [118] { return symbol(sym.LESS); }");
          { return symbol(sym.LESS);
          }
        case 80: break;
        case 36: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [119] { return symbol(sym.NGTR); }");
          { return symbol(sym.NGTR);
          }
        case 81: break;
        case 17: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [113] { return symbol(sym.SUB); }");
          { return symbol(sym.SUB);
          }
        case 82: break;
        case 53: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [88] { return symbol(sym.TYPE); }");
          { return symbol(sym.TYPE);
          }
        case 83: break;
        case 22: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [120] { return symbol(sym.GTR); }");
          { return symbol(sym.GTR);
          }
        case 84: break;
        case 45: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [135] { ++level; }");
          { ++level;
          }
        case 85: break;
        case 14: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [110] { return symbol(sym.R3); }");
          { return symbol(sym.R3);
          }
        case 86: break;
        case 28: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [76] { return symbol(sym.DO); }");
          { return symbol(sym.DO);
          }
        case 87: break;
        case 52: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [77] { return symbol(sym.ELSE); }");
          { return symbol(sym.ELSE);
          }
        case 88: break;
        case 42: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [150] { string.append(\'\\\"\'); }");
          { string.append('\"');
          }
        case 89: break;
        case 37: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [117] { return symbol(sym.NEQ); }");
          { return symbol(sym.NEQ);
          }
        case 90: break;
        case 7: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [103] { return symbol(sym.COLON); }");
          { return symbol(sym.COLON);
          }
        case 91: break;
        case 54: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [86] { return symbol(sym.THEN); }");
          { return symbol(sym.THEN);
          }
        case 92: break;
        case 55: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [153] { int tmp = yycharat(yylength() - 3) * 100 + yycharat(yylength() - 2) * 10 + yycharat(yylength() - 1);"+ZZ_NL+"  \t\t\t\t\t\t\t\t   if(tmp > 255) err(\"exceed ASCII code \\\\ddd!\"); else string.append((char)tmp); }");
          { int tmp = yycharat(yylength() - 3) * 100 + yycharat(yylength() - 2) * 10 + yycharat(yylength() - 1);
  								   if(tmp > 255) err("exceed ASCII code \\ddd!"); else string.append((char)tmp);
          }
        case 93: break;
        case 50: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [89] { return symbol(sym.VAR); }");
          { return symbol(sym.VAR);
          }
        case 94: break;
        case 58: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [90] { return symbol(sym.WHILE); }");
          { return symbol(sym.WHILE);
          }
        case 95: break;
        case 57: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [75] { return symbol(sym.BREAK); }");
          { return symbol(sym.BREAK);
          }
        case 96: break;
        case 32: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [81] { return symbol(sym.IF); }");
          { return symbol(sym.IF);
          }
        case 97: break;
        case 5: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [99] { return symbol(sym.NUM,new Integer(yytext())); }");
          { return symbol(sym.NUM,new Integer(yytext()));
          }
        case 98: break;
        case 12: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [108] { return symbol(sym.R2); }");
          { return symbol(sym.R2);
          }
        case 99: break;
        case 43: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [151] { string.append(\"\\\\\\\\\"); }");
          { string.append("\\\\");
          }
        case 100: break;
        case 51: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [152] { string.append((char)yycharat(yylength() - 1) - 64); }");
          { string.append((char)yycharat(yylength() - 1) - 64);
          }
        case 101: break;
        case 24: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [123] { return symbol(sym.OR); }");
          { return symbol(sym.OR);
          }
        case 102: break;
        case 31: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [82] { return symbol(sym.IN); }");
          { return symbol(sym.IN);
          }
        case 103: break;
        case 20: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [116] { return symbol(sym.EQ); }");
          { return symbol(sym.EQ);
          }
        case 104: break;
        case 49: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [79] { return symbol(sym.FOR); }");
          { return symbol(sym.FOR);
          }
        case 105: break;
        case 8: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [104] { return symbol(sym.SEMICOLON); }");
          { return symbol(sym.SEMICOLON);
          }
        case 106: break;
        case 47: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [83] { return symbol(sym.LET); }");
          { return symbol(sym.LET);
          }
        case 107: break;
        case 40: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [146] { string.append(\'\\n\'); }");
          { string.append('\n');
          }
        case 108: break;
        case 10: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [106] { return symbol(sym.R1); }");
          { return symbol(sym.R1);
          }
        case 109: break;
        case 48: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [84] { return symbol(sym.NIL); }");
          { return symbol(sym.NIL);
          }
        case 110: break;
        case 59: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [80] { return symbol(sym.FUNCTION); }");
          { return symbol(sym.FUNCTION);
          }
        case 111: break;
        case 6: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [102] { return symbol(sym.COMMA); }");
          { return symbol(sym.COMMA);
          }
        case 112: break;
        case 34: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [128] { err(\"Comment don\'t match!\"); }");
          { err("Comment don't match!");
          }
        case 113: break;
        case 18: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [114] { return symbol(sym.MUL); }");
          { return symbol(sym.MUL);
          }
        case 114: break;
        case 25: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [144] { string.append( yytext() ); }");
          { string.append( yytext() );
          }
        case 115: break;
        case 38: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [121] { return symbol(sym.NLESS); }");
          { return symbol(sym.NLESS);
          }
        case 116: break;
        case 15: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [111] { return symbol(sym.DOT); }");
          { return symbol(sym.DOT);
          }
        case 117: break;
        case 13: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [109] { return symbol(sym.L3); }");
          { return symbol(sym.L3);
          }
        case 118: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          scanner = new Lexer( new java.io.FileReader(argv[i]) );
          do {
            System.out.println(scanner.next_token());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
