package syntax_analyzer.compiler.visitor;

import code.*;
import syntax_analyzer.compiler.model.*;

/* Generated By:JJTree: Do not edit this line. .\MiniJavaParserVisitor.java */

public interface MiniJavaCheckVisitor {
	public String visit(SimpleNode node, Symbol thisClass, int times);

	public String visit(ASTRoot node, Symbol thisClass, int times);

	public String visit(ASTMainClass node, Symbol thisClass, int times);

	public String visit(ASTMainMethodDeclaration node, Symbol thisClass,
			int times);

	public String visit(ASTClassDeclaration node, Symbol thisClass, int times);

	public String visit(ASTClassExtendsDeclaration node, Symbol thisClass,
			int times);

	public String visit(ASTVariableDeclaration node, Symbol thisClass, int times);

	public String visit(ASTMethodDeclaration node, Symbol thisClass, int times);

	public String visit(ASTFormalParameter node, Symbol thisClass, int times);

	public String visit(ASTType node, Symbol thisClass, int times);

	public String visit(ASTArrayType node, Symbol thisClass, int times);

	public String visit(ASTBooleanType node, Symbol thisClass, int times);

	public String visit(ASTIntegerType node, Symbol thisClass, int times);

	public String visit(ASTIdentifier node, Symbol thisClass, int times);

	public String visit(ASTStatement node, Symbol thisClass, int times);

	public String visit(ASTBlock node, Symbol thisClass, int times);

	public String visit(ASTAssignmentStatement node, Symbol thisClass, int times);

	public String visit(ASTArrayAssignmentStatement node, Symbol thisClass,
			int times);

	public String visit(ASTIfStatement node, Symbol thisClass, int times);

	public String visit(ASTWhileStatement node, Symbol thisClass, int times);

	public String visit(ASTPrintStatement node, Symbol thisClass, int times);

	public String visit(ASTExpression node, Symbol thisClass, int times);

	public String visit(ASTAndExpression node, Symbol thisClass, int times);

	public String visit(ASTCompareExpression node, Symbol thisClass, int times);

	public String visit(ASTPlusExpression node, Symbol thisClass, int times);

	public String visit(ASTMinusExpression node, Symbol thisClass, int times);

	public String visit(ASTTimesExpression node, Symbol thisClass, int times);

	public String visit(ASTArrayLookUp node, Symbol thisClass, int times);

	public String visit(ASTArrayLength node, Symbol thisClass, int times);

	public String visit(ASTMessageSend node, Symbol thisClass, int times);

	public String visit(ASTIntegerLiteral node, Symbol thisClass, int times);

	public String visit(ASTTrueLiteral node, Symbol thisClass, int times);

	public String visit(ASTFalseLiteral node, Symbol thisClass, int times);

	public String visit(ASTNotExpression node, Symbol thisClass, int times);
}
