
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 05 14:04:40 CST 2008
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 15;
  public static final int FUNCTION = 39;
  public static final int GE = 21;
  public static final int UMINUS = 42;
  public static final int LPAREN = 5;
  public static final int INT = 46;
  public static final int ARRAY = 25;
  public static final int FOR = 30;
  public static final int MINUS = 13;
  public static final int RPAREN = 6;
  public static final int SEMICOLON = 4;
  public static final int AND = 22;
  public static final int LT = 18;
  public static final int TYPE = 41;
  public static final int NIL = 38;
  public static final int IN = 34;
  public static final int OR = 23;
  public static final int COMMA = 2;
  public static final int COMM = 43;
  public static final int PLUS = 12;
  public static final int ASSIGN = 24;
  public static final int IF = 26;
  public static final int ID = 44;
  public static final int DOT = 11;
  public static final int LE = 19;
  public static final int OF = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NEQ = 17;
  public static final int BREAK = 37;
  public static final int EQ = 16;
  public static final int LBRACK = 7;
  public static final int TIMES = 14;
  public static final int COLON = 3;
  public static final int LBRACE = 9;
  public static final int ELSE = 28;
  public static final int RBRACK = 8;
  public static final int TO = 31;
  public static final int WHILE = 29;
  public static final int LET = 33;
  public static final int THEN = 27;
  public static final int RBRACE = 10;
  public static final int END = 35;
  public static final int STRING = 45;
  public static final int GT = 20;
  public static final int VAR = 40;
  public static final int DO = 32;
}

