
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 04 01:12:39 CST 2009
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 11;
  public static final int UMINUS = 45;
  public static final int ARRAY = 5;
  public static final int LESS = 38;
  public static final int FOR = 10;
  public static final int AND = 42;
  public static final int SEMICOLON = 24;
  public static final int TYPE = 19;
  public static final int NIL = 15;
  public static final int OR = 43;
  public static final int IN = 13;
  public static final int COMMA = 22;
  public static final int DIV = 35;
  public static final int NUM = 4;
  public static final int ASSIGN = 44;
  public static final int IF = 12;
  public static final int DOT = 31;
  public static final int OF = 16;
  public static final int EOF = 0;
  public static final int GTR = 40;
  public static final int NGTR = 39;
  public static final int error = 1;
  public static final int MUL = 34;
  public static final int ADD = 32;
  public static final int NEQ = 37;
  public static final int BREAK = 6;
  public static final int EQ = 36;
  public static final int L3 = 29;
  public static final int L2 = 27;
  public static final int L1 = 25;
  public static final int COLON = 23;
  public static final int R3 = 30;
  public static final int R2 = 28;
  public static final int ELSE = 8;
  public static final int R1 = 26;
  public static final int TO = 18;
  public static final int WHILE = 21;
  public static final int LET = 14;
  public static final int THEN = 17;
  public static final int END = 9;
  public static final int STRING = 3;
  public static final int NLESS = 41;
  public static final int SUB = 33;
  public static final int VAR = 20;
  public static final int DO = 7;
  public static final int IDENTIFIER = 2;
}

